### ISSUE TITLE
Create Dockerfile / docker-compose setup

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/codespeed#2]
We want to run this on our existing `metrics` infrastructure. In order to deploy it, 
- [ ] we want to be able to run it as a container
- [ ] we want to add authentication (via reverse-proxy?), to allow running and posting benchmarks from CI

@ulope any thoughts on the above?

**Comment by ulope** [comment]
Yeah, sounds reasonable.
Adding basic auth via Traefik should be easy enough.

**Comment by konradkonrad** [comment]
- caddy for reverse proxy + basic auth
- data path for sqlite mounted from host
